"""more tables

Revision ID: 04a0cb2ae18d
Revises: d272cc39da06
Create Date: 2025-03-14 13:19:26.213945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04a0cb2ae18d'
down_revision: Union[str, None] = 'd272cc39da06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    cables_ends = postgresql.ENUM(
        name='cables_ends', create_type=False)
    power_ports_types = postgresql.ENUM(
        name='power_ports_types', create_type=False
    )
    power_outlets_types = postgresql.ENUM(
        name='power_outlets_types', create_type=False
    )
    power_outlets_feed_legs = postgresql.ENUM(
        name='power_outlets_feed_legs', create_type=False
    )
    op.create_table('power_ports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('max_draw', sa.Integer(), nullable=True),
    sa.Column('allocated_draw', sa.Integer(), nullable=True),
    sa.Column('type', power_ports_types, nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('cable', sa.BigInteger(), nullable=True),
    sa.Column('cable_end',cables_ends, nullable=True),
    sa.Column('mark_connected', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('_path_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('allocated_draw >= 0', name='allocated_draw_positive_check'),
    sa.CheckConstraint('max_draw >= 0', name='max_draw_positive_check'),
    sa.CheckConstraint('max_draw >= allocated_draw', name='allocated_draw_check'),
    sa.ForeignKeyConstraint(['_path_id'], ['cable_paths.id'], name=op.f('power_ports__path_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cable'], ['cables.id'], name=op.f('power_ports_cable_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('power_ports_device_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('power_ports_pkey'))
    )
    op.create_table('power_outlets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('device_model_id', sa.BigInteger(), nullable=False),
    sa.Column('power_port_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), server_default='000000', nullable=False),
    sa.Column('type', power_outlets_types, nullable=True),
    sa.Column('feed_leg', power_outlets_feed_legs, nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('cable', sa.BigInteger(), nullable=True),
    sa.Column('cable_end', cables_ends, nullable=True),
    sa.Column('mark_connected', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('_path_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['_path_id'], ['cable_paths.id'], name=op.f('power_outlets__path_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cable'], ['cables.id'], name=op.f('power_outlets_cable_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_model_id'], ['device_models.id'], name=op.f('power_outlets_device_model_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['power_port_id'], ['power_ports.id'], name=op.f('power_outlets_power_port_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('power_outlets_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('power_outlets')
    op.drop_table('power_ports')
    # ### end Alembic commands ###
