"""fix

Revision ID: 020adc0e9845
Revises: 04a0cb2ae18d
Create Date: 2025-03-14 15:47:33.934096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '020adc0e9845'
down_revision: Union[str, None] = '04a0cb2ae18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    cables_ends = postgresql.ENUM(
        "A",
        "B",
        name="cables_ends",
        create_type=False
    )
    op.create_table('cable_termination',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cable_id', sa.BigInteger(), nullable=False),
    sa.Column('cable_end', cables_ends, nullable=True),
    sa.Column('termination_id', sa.BigInteger(), nullable=False),
    sa.Column('termination_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cable_id'], ['cables.id'], name=op.f('cable_termination_cable_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['termination_id'], ['power_ports.id'], name=op.f('cable_termination_termination_id_fkey')),
    sa.ForeignKeyConstraint(['termination_type_id'], ['termination_type.id'], name=op.f('cable_termination_termination_type_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cable_termination_pkey')),
    sa.UniqueConstraint('termination_id', 'termination_type_id', name='cable_unique_termination')
    )
    op.add_column('power_outlets', sa.Column('device_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('power_outlets_device_model_id_fkey', 'power_outlets', type_='foreignkey')
    op.create_foreign_key(op.f('power_outlets_device_id_fkey'), 'power_outlets', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_column('power_outlets', 'device_model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_outlets', sa.Column('device_model_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('power_outlets_device_id_fkey'), 'power_outlets', type_='foreignkey')
    op.create_foreign_key('power_outlets_device_model_id_fkey', 'power_outlets', 'device_models', ['device_model_id'], ['id'], ondelete='CASCADE')
    op.drop_column('power_outlets', 'device_id')
    op.drop_table('cable_termination')
    # ### end Alembic commands ###
